remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Customer Requirements
description: A list of customer requirements for the configuration items phase of our deployment methodology. 
